//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assets.Resource.Tables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assets.Resource.Tables.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessDenied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is failed..
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define a correct Email or CellPhone number..
        /// </summary>
        internal static string BadEmailOrCellphone {
            get {
                return ResourceManager.GetString("BadEmailOrCellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BadRequest.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Phone number is already registered. If you forgot your Password try to use Forgat Password feature..
        /// </summary>
        internal static string CellPhoneAlreadyExists {
            get {
                return ResourceManager.GetString("CellPhoneAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should request forgoten password first..
        /// </summary>
        internal static string ChangingPasswordWithoutToken {
            get {
                return ResourceManager.GetString("ChangingPasswordWithoutToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for changing the password is liked an abnormal activity and it&apos;s logged..
        /// </summary>
        internal static string ChangingPasswordWithWrongToken {
            get {
                return ResourceManager.GetString("ChangingPasswordWithWrongToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionError.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DangerousRequest.
        /// </summary>
        internal static string DangerousRequest {
            get {
                return ResourceManager.GetString("DangerousRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefectiveCellPhone.
        /// </summary>
        internal static string DefectiveCellPhone {
            get {
                return ResourceManager.GetString("DefectiveCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefectiveEmail.
        /// </summary>
        internal static string DefectiveEmail {
            get {
                return ResourceManager.GetString("DefectiveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define your Email or CellPhone number..
        /// </summary>
        internal static string DefectiveEmailOrCellPhone {
            get {
                return ResourceManager.GetString("DefectiveEmailOrCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefectiveEntry.
        /// </summary>
        internal static string DefectiveEntry {
            get {
                return ResourceManager.GetString("DefectiveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define a Password..
        /// </summary>
        internal static string DefectivePassword {
            get {
                return ResourceManager.GetString("DefectivePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define your Username and Password..
        /// </summary>
        internal static string DefectiveUsernameOrPassword {
            get {
                return ResourceManager.GetString("DefectiveUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceIdNotFound.
        /// </summary>
        internal static string DeviceIdNotFound {
            get {
                return ResourceManager.GetString("DeviceIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceIsNotActive.
        /// </summary>
        internal static string DeviceIsNotActive {
            get {
                return ResourceManager.GetString("DeviceIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicatedValueFound.
        /// </summary>
        internal static string DuplicatedValueFound {
            get {
                return ResourceManager.GetString("DuplicatedValueFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is already registered. If you forgot your Password try to use Forgat Password feature..
        /// </summary>
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is not found..
        /// </summary>
        internal static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External authentication user email not found.
        /// </summary>
        internal static string ExternalAuthenticationEmailError {
            get {
                return ResourceManager.GetString("ExternalAuthenticationEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External authentication failed.
        /// </summary>
        internal static string ExternalAuthenticationFailed {
            get {
                return ResourceManager.GetString("ExternalAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External authentication user principal error.
        /// </summary>
        internal static string ExternalAuthenticationUserError {
            get {
                return ResourceManager.GetString("ExternalAuthenticationUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External signup with unknown ProviderId.
        /// </summary>
        internal static string ExternalAuthenticationWithUnknownProvider {
            get {
                return ResourceManager.GetString("ExternalAuthenticationWithUnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on link below to reset your password.
        /// </summary>
        internal static string ForgotPasswordEmailBody {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your forgotten password.
        /// </summary>
        internal static string ForgotPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on link below to reset your password.
        /// </summary>
        internal static string ForgotPasswordSMSBody {
            get {
                return ResourceManager.GetString("ForgotPasswordSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoToStepTwo.
        /// </summary>
        internal static string GoToStepTwo {
            get {
                return ResourceManager.GetString("GoToStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalServerError.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define a correct Email or CellPhone number..
        /// </summary>
        internal static string InvalidEmailOrCellPhone {
            get {
                return ResourceManager.GetString("InvalidEmailOrCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSigninAttempt.
        /// </summary>
        internal static string InvalidSigninAttempt {
            get {
                return ResourceManager.GetString("InvalidSigninAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NothingFound.
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is changed successfully..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined Password is not match with repeated one..
        /// </summary>
        internal static string PasswordsMissmatch {
            get {
                return ResourceManager.GetString("PasswordsMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneIsNotVerified.
        /// </summary>
        internal static string PhoneIsNotVerified {
            get {
                return ResourceManager.GetString("PhoneIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Phone number is not found..
        /// </summary>
        internal static string PhoneNotFound {
            get {
                return ResourceManager.GetString("PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestForVerificationCodeFirst.
        /// </summary>
        internal static string RequestForVerificationCodeFirst {
            get {
                return ResourceManager.GetString("RequestForVerificationCodeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetrieveLimit.
        /// </summary>
        internal static string RetrieveLimit {
            get {
                return ResourceManager.GetString("RetrieveLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenNotFound.
        /// </summary>
        internal static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re trying to signing in through the wrong way! buddy..
        /// </summary>
        internal static string UnofficialRequest {
            get {
                return ResourceManager.GetString("UnofficialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsupportedLanguage.
        /// </summary>
        internal static string UnsupportedLanguage {
            get {
                return ResourceManager.GetString("UnsupportedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsupportedTimeZone.
        /// </summary>
        internal static string UnsupportedTimeZone {
            get {
                return ResourceManager.GetString("UnsupportedTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserIsNotActive.
        /// </summary>
        internal static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerificationCodeHasBeenExpired.
        /// </summary>
        internal static string VerificationCodeHasBeenExpired {
            get {
                return ResourceManager.GetString("VerificationCodeHasBeenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongPassword.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongVerificationCode.
        /// </summary>
        internal static string WrongVerificationCode {
            get {
                return ResourceManager.GetString("WrongVerificationCode", resourceCulture);
            }
        }
    }
}
